# This is a basic workflow to help you get started with Actions

name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '15'
      
      - name: npm install
        run: |
          npm install

      - name: test
        run: |
          make test
